@port = {{$dotenv PORT}}
@baseUrl = http://localhost:{{port}}/api

### Get markers
# @name getMarkers
GET {{baseUrl}}/markers HTTP/1.1
Accept: application/json

### Insert a marker
# @name insertMarker
POST {{baseUrl}}/markers HTTP/1.1
Content-Type: application/json

{
    "type": "fish_hotspot3",
    "position": [9455.411, 8984.482]
}

### Get comments
# @name getComments
@markerId = {{getMarkers.response.body.$[0]._id}}

GET {{baseUrl}}/markers/{{markerId}}/comments HTTP/1.1
Accept: application/json

### Insert a comment
# @name insertComment
@markerId = {{getMarkers.response.body.$[0]._id}}
POST {{baseUrl}}/markers/{{markerId}}/comments HTTP/1.1
Content-Type: application/json

{
    "username": "[Coach] Leon",
    "message": "This is a test comment"
}

